name: smartto
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - matplotlib
  - tqdm
  - scikit-learn
  - jupyter
  - ipykernel
  - pip:
    - mediapipe
    - opencv-python
    - xgboost
    - optuna
    - imbalanced-learn
    - joblib
